"""
Django settings for homework project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#9g7yh8de)33at3bsj%=ylsfb%#8*!lzaqy!3b1k0d13d%yyzu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'index',
    'captcha',
    'tinymce',
]

MIDDLEWARE = [
    'index.views.AccessLogMiddleware',  # 将 AccessLogMiddleware 添加到中间件列表中，用于记录访问日志的
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'homework.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'homework.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME':'homework',
        'USER':'root',
        'PASSWORD':'hil@12345',
        'HOST':'127.0.0.1',
        'PORT':'3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=[os.path.join(BASE_DIR, 'static-files'),]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
SESSION_COOKIE_AGE = 3600   #设置会话时间为60分钟，单位为秒  

#忘记密码发送电子邮件
#我这里的是163邮箱的
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.163.com'  # 使用的SMTP邮件服务提供商的SMTP服务器地址
EMAIL_PORT = 465  # 使用的SMTP邮件服务提供商的SMTP服务器端口号
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_TIMEOUT = 5  # 设置连接到SMTP服务器的最长时间，单位：秒
EMAIL_HOST_USER = '*'  # 发送邮件的邮箱地址
EMAIL_HOST_PASSWORD = '*'  # 发送邮件的邮箱授权码
DEFAULT_FROM_EMAIL = '*'  # 默认发件人邮箱



LOGGING = {  # 定义 LOGGING 配置字典
    'version': 1,  # 配置字典的版本号
    'disable_existing_loggers': False,  # 禁用已存在的日志记录器
    'handlers': {  # 配置日志处理器
        'access_log': {  # 配置名为 access_log 的日志处理器
            'class': 'logging.handlers.TimedRotatingFileHandler',  # 使用 TimedRotatingFileHandler 类
            'filename': 'logs/access.log',  # 日志文件路径
            'when': 'midnight',  # 分割时间为每天的午夜
            'backupCount': 15,  # 最多保留 15 个日志文件
            'formatter': 'access',  # 使用名为 access 的日志格式
        },
    },
    'loggers': {  # 配置日志记录器
        'access_log': {  # 配置名为 access_log 的日志记录器
            'handlers': ['access_log'],  # 使用名为 access_log 的日志处理器
            'level': 'INFO',  # 设置记录日志的级别为 INFO
            'propagate': False,  # 禁止向父级记录器传播日志消息
        },
    },
    'formatters': {  # 配置日志格式
        'access': {  # 配置名为 access 的日志格式
            'format': '%(asctime)s %(message)s',  # 设置日志记录的格式
            'datefmt': '%Y-%m-%d %H:%M:%S',  # 设置时间戳的格式
        },
    },
}