# Generated by Django 2.1 on 2023-06-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('password', models.CharField(default='852033170f61b7f154b83d24425fd23bf44507d4f7aad1dcaf4e22c42b8ded5c', max_length=64, verbose_name='密码')),
            ],
        ),
    ]
