# Generated by Django 3.2.19 on 2023-06-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20230607_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionTask1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='任务名字')),
                ('creator', models.CharField(max_length=100, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('file_path', models.CharField(max_length=200, verbose_name='收集文件路径')),
            ],
        ),
        migrations.DeleteModel(
            name='CollectionTask',
        ),
    ]
