# Generated by Django 3.2.19 on 2023-06-07 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20230607_0851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollectionTask1',
            new_name='CollectionTask',
        ),
    ]
