# Generated by Django 3.2.19 on 2023-06-07 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_collectiontask1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectionTask1',
        ),
    ]
