# Generated by Django 3.2.19 on 2023-06-07 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20230607_0942'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollectionTask1',
            new_name='CollectionTask',
        ),
    ]
