# Generated by Django 3.2.19 on 2023-06-07 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_rename_collectiontask1_collectiontask'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollectionTask',
            new_name='Collection_Task',
        ),
    ]
