# Generated by Django 3.2.19 on 2023-06-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_rename_collectiontask_collection_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collection_Task',
            new_name='CollectionTask',
        ),
    ]
