# Generated by Django 3.2.19 on 2023-06-07 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_rename_collection_task_collectiontask'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollectionTask',
            new_name='CollectionTask1',
        ),
    ]
