# Generated by Django 3.2.19 on 2023-06-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_rename_collectiontask_collectiontask1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollectionTask1',
            new_name='CollectionTask',
        ),
    ]
