# Generated by Django 3.2.19 on 2023-06-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_rename_collectiontask1_collectiontask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectionTask',
        ),
    ]
