# Generated by Django 3.2.19 on 2023-06-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_collectiontask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectionTask',
        ),
    ]
