# Generated by Django 3.2.19 on 2023-06-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_auto_20230608_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionrecord',
            options={'verbose_name': '收集记录', 'verbose_name_plural': '收集记录'},
        ),
        migrations.RemoveField(
            model_name='collectiontask',
            name='submit_time',
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='user',
            field=models.CharField(max_length=100, verbose_name='提交用户'),
        ),
    ]
