# Generated by Django 3.2.19 on 2023-06-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_auto_20230608_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiontask',
            name='create_time',
            field=models.DateTimeField(default='2023-06-09 13:28:45', verbose_name='创建时间'),
        ),
        migrations.DeleteModel(
            name='CollectionRecord',
        ),
    ]
