# Generated by Django 3.2.19 on 2023-06-09 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_auto_20230609_1328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectionTask',
        ),
    ]
