# Generated by Django 3.2.19 on 2023-06-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0021_delete_collectiontask'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='任务名字')),
                ('creator', models.CharField(max_length=100, verbose_name='创建人')),
                ('create_time', models.DateTimeField(default='2023-06-09 13:30:29', verbose_name='创建时间')),
                ('file_path', models.CharField(max_length=200, verbose_name='收集文件路径')),
            ],
        ),
    ]
