# Generated by Django 3.2.19 on 2023-06-13 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_collectiontask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiontask',
            name='create_time',
            field=models.DateTimeField(default='2023-06-13 14:02:23', verbose_name='创建时间'),
        ),
        migrations.CreateModel(
            name='TaskMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pattern', models.CharField(blank=True, max_length=100, null=True)),
                ('creator', models.CharField(blank=True, max_length=100)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.collectiontask')),
            ],
        ),
    ]
