# Generated by Django 3.2.19 on 2023-06-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_auto_20230615_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collectiontask',
            name='create_time',
            field=models.DateTimeField(default='2023-06-18 17:52:12', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default='2023-06-18 17:52:12', verbose_name='创建时间'),
        ),
    ]
