# Generated by Django 3.2.19 on 2023-06-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_auto_20230618_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiontask',
            name='create_time',
            field=models.DateTimeField(default='2023-06-19 11:33:48', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default='2023-06-19 11:33:48', verbose_name='创建时间'),
        ),
    ]
